// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWeh74a38rElbOzaXc6CVJQvgE0TpTPgI',
    appId: '1:534442766167:android:b7338813871d22dadbd812',
    messagingSenderId: '534442766167',
    projectId: 'govideoeditor-a1523',
    databaseURL: 'https://govideoeditor-a1523-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'govideoeditor-a1523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhH_Y1K_A9Jwpl5NgybNkafWsUk_rKLKU',
    appId: '1:534442766167:ios:27ffa13fcfa5fa93dbd812',
    messagingSenderId: '534442766167',
    projectId: 'govideoeditor-a1523',
    databaseURL: 'https://govideoeditor-a1523-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'govideoeditor-a1523.firebasestorage.app',
    iosBundleId: 'com.example.govideoeditor',
  );
}
